language: php

stages:
  - Smoke Testing
  - Test

php:
  # 7.1 is included in the matrix below, with coverage
  - 7.2
  - 7.3
  # 7.4 is included in the matrix below, as base version for smoke testing

env:
  - CALCULATOR=GMP
  - CALCULATOR=BCMath
  - CALCULATOR=Native

before_script:
  - |
    if [ "x$COVERAGE" != "xyes" ]; then
      phpenv config-rm xdebug.ini
    fi
  - composer install

script:
  - |
    if [ "x$COVERAGE" == "xyes" ]; then
      mkdir -p build/logs && vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    else
      vendor/bin/phpunit
    fi

after_script:
  - |
    if [ "x$COVERAGE" == "xyes" ]; then
      vendor/bin/php-coveralls -v
    fi

jobs:
  include:
    - stage: Smoke Testing
      php: 7.4
      name: Psalm
      script: vendor/bin/psalm --show-info=false --no-progress
    - stage: Smoke Testing
      php: 7.4
      env: CALCULATOR=GMP
    - stage: Smoke Testing
      php: 7.4
      env: CALCULATOR=BCMath
    - stage: Smoke Testing
      php: 7.4
      env: CALCULATOR=Native
    - stage: Tests
      php: 7.1
      env: CALCULATOR=GMP COVERAGE=yes
    - stage: Tests
      php: 7.1
      env: CALCULATOR=BCMath COVERAGE=yes
    - stage: Tests
      php: 7.1
      env: CALCULATOR=Native COVERAGE=yes
